### ISSUE TITLE
missing and mismatched configuration variables

### ISSUE THREAD

**Issue by raleonardo** [danielkoster/ansible-role-transmission-daemon#11]
after restarting transmission daemon, when applying the role one can notice the default values were overwriten for some variables.

*transmission-daemon 2.94-2+deb10u2` on `debian-buster`

```
TASK [vendor/danielkoster.transmission-daemon : transmission-daemon | Create settings file] ***************************************************************************************
--- before: /etc/transmission-daemon/settings.json
+++ after: /Users/raleonardo/.ansible/tmp/ansible-local-427343q2wub3n/tmpjeiuzynz/settings.json.j2
@@ -37,7 +37,7 @@
     "pex-enabled": true,
     "port-forwarding-enabled": false,
     "preallocation": 1,
-    "prefetch-enabled": true,
+    "prefetch-enabled": 1,
     "queue-stalled-enabled": true,
     "queue-stalled-minutes": 30,
     "ratio-limit": 2,
@@ -46,15 +46,12 @@
     "rpc-authentication-required": true,
     "rpc-bind-address": "0.0.0.0",
     "rpc-enabled": true,
-    "rpc-host-whitelist": "",
-    "rpc-host-whitelist-enabled": true,
...
     "rpc-whitelist-enabled": true,
-    "rpc-whitelist-host-enabled": true,
     "scrape-paused-torrents-enabled": true,
```

`prefetch-enabled`: should be defaulted to  'true'  instead of '1'
`rpc-host-whitelist`and  `rpc-host-whitelist-enabled`are missing in the template and defaults

`rpc-whitelist-host-enabled` is always added by transmission but it's undocumented (maybe transmission bug)

**Comment by raleonardo** [comment]
I have a fix ready, but can't push another branch. how can I pull request it?

**Comment by danielkoster** [comment]
Hi, good catch!

You can create a pull request by forking this repository, committing your changes to your fork, and than creating a pull request to merge your changes into this repo. Let me know if that works out, otherwise I'll try to fix it on this repo directly. Thanks for your contribution!

**Comment by raleonardo** [comment]
Cool!
Done!
