### ISSUE TITLE
handler doesnt run reload inside chroot

### ISSUE THREAD

**Issue by sedlund** [danielkoster/ansible-role-transmission-daemon#3]
I'm working inside a chroot, and was having issues when the settings template changed and the daemon not reloading.

I found that when manually invoking invoke-rc.d I get this error:

# sudo invoke-rc.d transmission-daemon reload
Running in chroot, ignoring request.
invoke-rc.d: policy-rc.d denied execution of reload.

and it exits with 0 status, so ansible thinks everything is great.

I changed the handler to be:
---

- name: "transmission-daemon | reload settings"
  command: "invoke-rc.d --force transmission-daemon reload"

and this seems to work as intended for me.

**Comment by danielkoster** [comment]
Hi! Thanks for your report. I've done a bit of researching into this and I think this is a result of how systemd works inside of a chroot. It appears it is not easily possible to start daemons who are not in the chroot, from that chroot. Adding `--force` to the call ignores the message, but does not actually change the end result of the call.

I think this is not an error in how this is being called from the ansible role, but a side-effect of how systemd works in a chroot. So I also think I am not able to resolve this from the ansible role, as it is not the source of the error. Would you agree?

See also:
http://0pointer.de/blog/projects/changing-roots.html
https://superuser.com/questions/688733/start-a-systemd-service-inside-chroot

**Comment by sedlund** [comment]
Thanks for taking a look.

I solved this by changing the policy-rc.d file:
echo exit 0 | sudo tee /usr/sbin/policy-rc.d

By default it is 'exit 101' which causes invoke-rc.d to not run inside chroots.

Some background.  I'm running ChromeOS with a crouton chroot of Ubuntu Artful.  The system does not use systemd at all.  When starting the chroot, /etc/rc.local is called and it starts the services that I want - like transmission - using simple entries like '/etc/init.d/transmission-daemon start'.

invoke-rc.d is not part of systemd - it just calls the SystemV transmission-daemon init script.

You could actually switch the ansible handler to use the service module.  I've tested it inside the chroot with the updated policy-rc.d and it correctly detects that systemd is not running in chroot and calls invoke-rc.d to reload.  On a systemd system, it should call systemctl reload.

Either way - this can be closed.  I appreciate your time.

**Comment by danielkoster** [comment]
Ah yes, calling `invoke-rc.d` directly from a command might have been a tad too much. I have changed this to use Ansible's own service-module which should handle this correctly, as you mentioned. This should make it work in the situation you've described, even though you have already found a workaround :)

Thanks again for your input!
